FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    pydantic

COPY processor_servers ./processor_servers

EXPOSE 8001 8002 8003

CMD ["uvicorn", "processor_servers.processor_a.main:app", "--host", "0.0.0.0", "--port", "8001"]